name: Deploy

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/setup-node@v2
        with:
          node-version: "16.3"
          cache: "yarn"

      - name: Build JS files
        env:
          SLUG: intro-section-with-dropdown-navigation
        run: |
          yarn
          yarn build --base "https://halivert.dev/$SLUG/"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.3.3
        with:
          branch: gh-pages
          folder: dist
